# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52cedc9697ba5eea1dd0a702c89d869179e7be499585fbeaa68022a0a3b712a66b3e91643f7142344d00ef05a2da4f52565e0fe7e727b24af225fdb854b57f64

test:
  secret_key_base: 57e6586c82c7a3829b7e5ba539a5f33f19a67854f0dad7f7e155ba43fef8faf81658c55da1ec07a404c5e05f8bb36b591cfce743eb030006820f84e504d4e3ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
